few_shot_examples:
  prefix: ""
  template: |-
    Given the following problem, reason and give a final answer to the problem.
    Problem: {problem}
    Your response should end with "The final answer is \boxed{{[answer]}}" where [answer] is the response to the problem.{user_end}{assistant_begin}{solution}{assistant_end}{user_begin}
  suffix: ""
  examples_type: math_text_with_code

user: |-
  {examples}Given the following problem, reason and give a final answer to the problem.
  Problem: {problem}
  Your response should end with "The final answer is \boxed{{[answer]}}" where [answer] is the response to the problem.
