few_shot_examples:
  prefix: ""
  template: |-
    Question:
    {problem}{user_end}{assistant_begin}{solution}{assistant_end}{user_begin}
  suffix: ""
  examples_type: math_text_with_code

system: ""

user: |-
  Here are some examples of questions and solutions followed by a new question that you need to solve.
  Make sure to put the answer (and only answer) inside \\boxed{{}}.

  {examples}
  Question:
  {problem}
